/* This component renders the output that will be generated by the large language model */

import { useState, useEffect } from 'react'
import axios from 'axios'
import {Typography, Box} from "@mui/material"
import { red } from "@mui/material/colors";

const PromptOutput = ({ prompt }) => {
    const [output, setOutput] = useState('')

    useEffect(() => {
        axios
            .post('PaLM2 api url', { prompt })
            .then((response) => setOutput(response.data.output))
            .catch((error) => console.error('Error fetching results: ', error))
    }, [prompt])

    return( <div className='prompt-output'>
        <Box flex={6}  bgcolor={red} sx={{
            maxHeight: "700px", // Set the desired maximum height
            overflow: "auto", // Enable scrolling when content exceeds the height
            
          }}
          >
            <Typography variant="p" style={{color: "black", backgroundColor: "grey"}}>
                {output}
            </Typography>

        </Box>

    </div>
    )
}

export default PromptOutput
