/* This component renders the output that will be generated by the large language model */

import { useState, useEffect } from 'react'
import axios from 'axios'
import { Typography, Box, LinearProgress } from '@mui/material'
import { red } from '@mui/material/colors'

const PromptOutput = ({ prompt }) => {
    const [output, setOutput] = useState('')


    useEffect(() => {
        axios
            .post('http://127.0.0.1:8080/chat', null, {
                params: {
                    human_msg: prompt,
                },
                headers: {
                    accept: 'application/json',
                },
            })
            .then((response) => setOutput(response.data.response))
            .catch((error) => console.error('Error fetching results: ', error))
            const OutputProgressBar = document.getElementById("progressbar")
        OutputProgressBar.style.display = "none"
    }, [prompt])
    

    return (
        
            <div className='prompt-output'>
                
                <Box
                    
                    flex={6}
                    bgcolor={red}
                    sx={{
                        maxHeight: '605px', // Set the desired maximum height
                        // overflow: "auto", // Enable scrolling when content exceeds the height
                    }}
                > 

                    <Typography
                        variant='p'
                        style={{ color: 'black', backgroundColor: 'grey' }}
                    >
                        {output}
                    </Typography>
                </Box>
                <LinearProgress id ="progressbar" color="secondary" style={{ top: 599 , borderRadius: 3 , width: 915 , left: 4, display: 'none'}} />
            </div>
    )
}

export default PromptOutput
